### ISSUE TITLE
Testnet Launch Issue Tracker

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-front-end#54]
- [x] Add Warning about inability to use Mobile 
- [x] ~~Fix Visual Issues on Mobile~~ (irrelevant now)
- [x] Add download links for signer and polkadot.js

**Comment by dansofter** [comment]
Add a disclaimer to prevent users refreshing the page in case manta-signer gets delayed

**Comment by Kevingislason** [comment]
- [ ] Manta signer can only do one transaction bug

**Comment by dansofter** [comment]
> * [ ]  Add Warning about inability to use Mobile
> * [ ]   Fix Visual Issues on Mobile
> * [x]  Add download links for signer and polkadot.js

@bhgomes @stechu 
Mind adding a screenshot for the visual issues on mobile?
I can't replicate anything wrong.

**Comment by bhgomes** [comment]
@dansofter We can ignore that now once we have the mobile modal implemented.
